# To give a player these messages give them the announcerplus.join.default
#    and announcerplus.quit.default permissions
#
# If set, this permission will be required to see these join/quit messages:
seePermission: ""
# Sent to the player joining (optional)
joinMessages:
  - "<hover:show_text:'<yellow>Username</yellow><gray>:</gray> {user}'>{nick}</hover> <yellow>joined the game"
  - "<center><rainbow><italic>Welcome,</rainbow> {user}<yellow>!"
  - "<center><gradient:black:white>------------------</gradient><gradient:white:black>------------------</gradient>"
  - "This server is using <blue>Announcer<italic>Plus<reset>!"
  - "<gradient:green:white>Configure these messages by editing the config files!"
# Sent to everyone but the player joining (optional)
joinBroadcasts:
  - "<hover:show_text:'<yellow>Username</yellow><gray>:</gray> {user}'>{nick}</hover> <yellow>joined the game"
# Sent to players online when player quits (optional)
quitBroadcasts:
  - "<hover:show_text:'<yellow>Username</yellow><gray>:</gray> {user}'>{nick}</hover> <yellow>left the game"
# play this sound to the player who joins (optional)
#   You may list more then one sound separated by a comma
joinSounds: "minecraft:entity.strider.happy,minecraft:entity.villager.ambient,minecraft:block.note_block.cow_bell"
# if more than one join sound is listed, this will determine if a random one, or if all of the sounds are played.
randomJoinSound: true
# played to all players except the joining player on join (optional)
joinBroadcastSounds: "minecraft:entity.enderman.teleport,minecraft:entity.cow.ambient"
randomJoinBroadcastSound: true
# played to all players on player quit
quitSounds: "minecraft:entity.enderman.teleport"
randomQuitSound: true
# show this title/subtitle to the joining player (optional)
title:
  fadeInSeconds: 1
  durationSeconds: 5
  fadeOutSeconds: 1
  # either of these may be left blank
  title: "<bold><italic><rainbow>Welcome</rainbow><yellow>!"
  subTitle: "<gradient:blue:light_purple>{user}"
# show this actionbar to the player on join (optional)
actionBar:
  durationSeconds: 6
  text: "<gradient:green:blue>|||||||||||||||||||||</gradient><gradient:blue:green>||||||||||||||||||</gradient>"
# these commands will be run as the player on join (optional)
runAsPlayerJoinCommands:
  - "ap about"
# these commands will be run as console on join (optional)
joinCommands:
  - "minecraft:give %player_name% dirt"
# these commands will be run as console on quit (optional)
quitCommands:
  - "broadcast %player_name% left"