# To give a player these messages give them the announcerplus.join.default
#    and announcerplus.quit.default permissions
# If set, this permission will be required to see these join/quit messages
seePermission: ""
# Sent to the player joining
joinMessages:
  - "<hover:show_text:'<yellow>Username</yellow><gray>:</gray> {user}'>{nick}</hover> <yellow>joined the game"
  - "<rainbow><italic>Welcome,</rainbow> {user}<yellow>!"
  - "This server is using <blue>Announcer<italic>Plus"
# Sent to everyone but the player joining
joinBroadcasts:
  - "<hover:show_text:'<yellow>Username</yellow><gray>:</gray> {user}'>{nick}</hover> <yellow>joined the game"
# Sent to players online when player quits
quitBroadcasts:
  - "<hover:show_text:'<yellow>Username</yellow><gray>:</gray> {user}'>{nick}</hover> <yellow>left the game"
