name: Build with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '16'
    - name: Build with Gradle
      run: ./gradlew clean build
    - run: mkdir staging && cp build/libs/AnnouncerPlus*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
